{
 "title": "BentoML DB-BHCN",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Target drift",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:cat_target_drift:drift{instance=\"localhost:5000\"}"
    }
   ]
  },
  {
   "title": "Response time distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(BENTOML_db_bhcn_request_duration_seconds_bucket{endpoint=\"/predict\",http_response_code=\"200\",instance=\"localhost:8000\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "% of drifted features",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:share_drifted_features{instance=\"localhost:5000\"}"
    }
   ]
  },
  {
   "title": "Data drift by feature over time",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 20, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "evidently:data_drift:p_value{instance=\"localhost:5000\", feature=~'.*0'}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Drifted features count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features{instance=\"localhost:5000\"}"
    }
   ]
  }
 ]
}