{
 "title": "BentoML Tfidf-LSGD",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total requests served",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BENTOML_tfidf_lsgd_request_total{endpoint=\"/predict\",http_response_code=\"200\"}"
    }
   ]
  },
  {
   "title": "Response times",
   "type": "bargauge",
   "description": "Response times by responses within the selected period.",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(BENTOML_tfidf_lsgd_request_duration_seconds_bucket{endpoint=\"/predict\",http_response_code=\"200\",instance=\"localhost:3000\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response times over time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(BENTOML_tfidf_lsgd_request_duration_seconds_bucket{endpoint=\"/predict\",http_response_code=\"200\"}[1m])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}