{
 "title": "Tfidf+LeafSGD",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Classification performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% of drifted features",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:share_drifted_features{}"
    }
   ]
  },
  {
   "title": "Target drift",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:cat_target_drift:drift{instance=\"monitoring:5001\"}"
    }
   ]
  },
  {
   "title": "Data drift by feature over time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    { "expr": "evidently:data_drift:p_value{}", "legendFormat": "{{feature}}" }
   ]
  },
  {
   "title": "Drifted features count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features"
    }
   ]
  },
  { "title": "API performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests/s",
   "type": "stat",
   "description": "Average number of requests per second within the dashboard's currently selected time range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(BENTOML_Tfidf_LSGD_request_total{endpoint=\"/predict\",instance=\"inference:5000\"}[$__range])"
    }
   ]
  },
  {
   "title": "Response time distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(BENTOML_Tfidf_LSGD_request_duration_seconds_bucket{endpoint=\"/predict\",http_response_code=\"200\",instance=\"inference:5000\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Adaptive microbatching batch size",
   "type": "bargauge",
   "description": "Distribution of microbatch sizes as marshalled by BentoML.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BENTOML_Tfidf_LSGD_mb_batch_size_bucket{endpoint=\"predict\",instance=\"inference:5000\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}