global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: prometheus

  honor_labels: true
  static_configs:
  - targets:
    - localhost:5000  # all of our Bento models run on this port by default
    - localhost:6000  # for Evidently
